### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by AhmadCodes** [jdfxzzy/DPMN#4]
Pretrained weights links are not working, can you please update the links or provide with working links?

**Comment by jdfxzzy** [comment]
I tried the links just now, but I find that they works well. I updated the links about a month before, and the old links are closed. Maybe you visited these old links in the forked version of this repository. Please try the new links in the readme file:
DPMN with TATT-ASTER as PSN: [https://pan.baidu.com/s/1grBb_RlR1QMCgs54dW4bfw](https://pan.baidu.com/s/1grBb_RlR1QMCgs54dW4bfw), password: jtei.
DPMN with TATT-CRNN as PSN: [https://pan.baidu.com/s/1e0Qiq21vNH0Xq2kLkwQuig](https://pan.baidu.com/s/1e0Qiq21vNH0Xq2kLkwQuig), password: 8r6g.
DPMN with TATT-MORAN as PSN: [https://pan.baidu.com/s/1ch_UHrupjuCs5eaiWfE02Q](https://pan.baidu.com/s/1ch_UHrupjuCs5eaiWfE02Q), password: 8hrz.
