### ISSUE TITLE
question about image size

### ISSUE THREAD

**Issue by 0-Maxwei-0** [jdfxzzy/DPMN#8]
hello, thanks for your excellent work! I am a beginner of SR.  When I was working on some OCR tasks, I found that I needed to do super-resolution on some images. I understand that your job requires setting the image size to 16*64, but my image sizes are relatively large (300*2500). If I scale the images to that size, the text in the images will be squeezed together and unclear. In this case, can I still use your work for super-resolution? Are all models trained on the Textzoom dataset unsuitable? Is there any suitable algorithm for text super-resolution? Thank you very much.

**Comment by jdfxzzy** [comment]
I think if you directly use our work, sub-optimal results will be obtained. However, I still encourage you to have a try.
